### ISSUE TITLE
This code is taken from Pololu

### ISSUE THREAD

**Issue by MAWoodMain** [Protocentral/protocentral_vl53l0x#1]
I have noticed that this library is not your own work and it is a plain copy of this https://github.com/pololu/vl53l0x-arduino
You do not have the right to apply your own licencing too it without accrediting the author.

**Comment by awhitchurch** [comment]
Thank you for pointing this out. We apologize for this, this was a genuine mistake on our part. The Arduino library has been copied from the Pololu code. However, the processing code is our own. We will update the license and the attribution immediately.
